# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoulSafe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoulSafe
  pod 'IQKeyboardManagerSwift'
  pod 'GrowingTextView', '0.7.2'
  pod 'FirebaseAuth', '9.0'
  pod 'FirebaseFirestore', '9.0'
  pod 'FirebaseStorage', '9.0'
  pod 'Kingfisher', '~> 7.0'

end
